// export an array of journal prompts
export const journalPromts = [
    "What did you learn today?",
    "What are you grateful for today?",
    "What are your plans for this weekend?",
    "Write 5 affirmations for when you are feeling low.",
    "What is the best book you have read recently?",
    "How have you grown this year?",
    "What are the most important life lessons you have learned?",
    "Have trouble sleeping? What’s keeping you up?",
    "What is the last dream you remember?",
    "What is your favorite memory of the day?",
    "What is your favorite memory of the week?",
    "What is your favorite memory of the month?",
    "What is your favorite memory of the year?",
    "What is your favorite memory of all time?",
    "Name the three biggest priorities in your life right now.",
    "What are your biggest fears?",
    "What are your biggest strengths?",
    "What are your biggest regrets?",
    "Write down your ultimate way to relax.",
    "What is your favorite quote?",
    "What would you do if you were granted three wishes?",
    "Name three bad habits you would like to change.",
    "What is your favorite thing to do in your free time?",
    "Think about someone you really love. Write about the person that came to mind.",
    "List the best 0 moments of your life so far.",
    "Write about 5 amazing childhood memories you are grateful for.",
    "Write about something that made you smile today.",
    "Which people in your life are you most grateful for.",
    "When were you last surprised?",
    "Name a challenge you have overcome and how it helped you to grow.",
    "What are your top 0 goals?",
    "What are your top 0 fears?",
    "Who is someone that inspires you and why?",
    "Name a skill you would love to learn.",
    "Do you have an embarrassing moment that still makes you cringe?",
    "What is a memory that always makes you smile?",
    "If you could go back in time, where would you go?",
    "Describe your dream vacation.",
    "Where do you think you will be in five years?",
    "If you were to die today what would like people to say about you?",
    "What is your proudest accomplishment?",
    "If you could be anybody, who would you be?",
    "What is the most important aspect of your life and why?",
    "Where would you travel, if you could go anywhere",
    "What time period you would like to be born in",
    "What extinct animal would you bring back, if you could",
    "What profession would you have chosen, if not your current one",
    "What book setting would you like to visit, if you could",
    "Given the chance to give your child only one quality as a person, which would you choose", "How about if that choice were unavailable, what would be your second and maybe third choices", "Why are these so important to you",
    "Which superpower would you choose to have if you had the option and why", "Conversely, which superhero do you find to be the most overrated and why",
    "You have one week to do whatever you want, all-expenses-paid, what things would you want to do", "Where would you go",
    "If your best friend came to you depressed and upset like you've never seen before, how would you react",
    "In what ways do you sometimes wish to act to be a better friend, but don't", "Why do you find yourself unable to do these things",
    "You have one hour to come up with the most interesting television show you can and describe/pitch it",
    "Consider some of the parents others had growing  ", "What type of person would you be if you had those situations",
    "What if your life had been harder or easier", "How do you think you'd be different",
    "Am I happy with my job, life, and situation", "What parts are good", "What parts are bad",
    "If I could change one thing about my spouse/lover, what would I change",
    "What is the greatest vacation I have taken and what lessons can I take from it",
    "If you won a million dollars but had to give it all away, who would you give it to and why",
    "What was your first pet", "Why did you choose this pet",
    "If you could build a car customized just for you, what would it contain",
    "What did you want to be when you grew up",
    "If you had to write your life story, what would the title be",
    "How do you feel when you see something beautiful", "Have you ever seen something so beautiful it makes you cry",
    "What are you thankful for",
    "What do you think about as you are falling asleep",
    "What is the most beautiful thing you have ever seen",
    "What is your favorite thing to do outdoors",
    "What would you write in a letter you could send back in time to yourself as a teen-ager",
    "What would you write in a letter you could send forward in time to yourself in 0 years",
    "When did you first realize you would someday be old or someday die",
    "Explain how you chose your career path",
    "When have you realized you were really wrong in your judgment about someone",
    "How do you react when you realize you've made a mistake",
    "What situation has caused you to confront your ethics recently",
    "If you had to sacrifice one of your senses (taste, touch, smell, sight, hearing), which would you choose and why",
    "What about a goal makes you most likely to procrastinate",
    "What would it be like to be in a tornado",
    "Where would you go to relax and why",
    "How do you make ice cream",
    "Why does the ocean have a tide",
    "Who has more power the government or the people",
    "Did I recently have an interesting conversation",
    "What is a scary dream that I remember from my past",
    "Who is the person that I feel has altered the course of my morals and values, and how did they effect me",
    "Where do I see myself, so far as my goals, personal development, residence, or job, in five years, and do I have a plan to arrive at this destination",
    "What is my earliest or happiest memory",
    "Which amendment to the constitution is the most important to you and why",
    "Is speech always free", "When and where might it not be free",
    "Put yourself in Anne Frank's place how would you have survived",
    "If you witnessed a fight at school would you report it", "What could the repercussions be if you told the truth",
    "What was(will be) the first thing that you did(do) when you got your driver's license",
    "What would you do if you woke up one morning with a tail",
    "How would you react if you were to find out you would be the first child in space",
    "Who would you most like to be like if you could change your personality",
    "If you were born in another time, what time would you choose and why",
    "Where would you most like to watch the sun come up",
    "How do you think instant riches would affect your friendships and familial relationships",
    "How do you think sudden loss of millions would affect your familial relationships and friendships",
    "How do you imagine humans would move to Mars in the event of world wide catastrophe",
    "If you were elected President, what do you think would be your most difficult tasks",
    "Describe something you feel most passionate about to a complete stranger",
    "Describe your favorite memory about an amusement park or county fair you visit",
    "When was the last time you lied",
    "What was your closest brush with death",
    "Where would you want to live if Earth was uninhabitable",
    "Remember the last time you spoke to a person who later died",
    "If you were to die tomorrow, what would you want your last words to be",
    "Write about the last time weather scared you",
    "Who was the best teacher you ever had, and why",
    "Describe your favorite song",
    "When were you the happiest this year",
    "What would you do on a snow day",
    "What are you saving up for",
    "What caused me to wince today",
    "Who did I run in to today that I would like to spend more time with",
    "What tempted me today",
    "What yes or no questions should I decide by flipping a coin",
    "What trait did you admire in a relative, friend, classmate, or coworker today",
    "How do you feel when you stare at the stars",
    "What would you say to your loved ones if you could tell them absolutely anything",
    "If you could tell your boss what you really want to do in your job, what would it be",
    "How are you going to make tomorrow a joyful day",
    "Recall a place, person or event, what emotion do you remember feeling most strongly",
    "If you could return in time to a set time to relive it, but not change anything, what would you choose and why",
    "What is your strongest memory, as a child, of your parents and what were you all doing at the time",
    "You are given 24 hours to do whatever you would like What do you do and why",
    "You have to invite 5 people to dinner, dead or alive Who do you invite and why",
    "What makes your favorite song so special. How do you personally relate to it",
    "What are some colors you see the most in your every day life",
    "What is your fondest memory of an animal or pet you once had",
    "If you could go back and relive one of your past trips, whom from your current entourage would you take with you",
    "What happens in the latest movie you saw",
    "Can you picture yourself in the shoes of any of the protagonists",
    "What is the best gift you've ever given someone", "Why do you like/dislike the city where you live",
    "What's your most treasured memory from high school",
    "Which friend has had the greatest impact on your life and why",
    "Which photo of yourself do you hate the most, and why",
    "Who inspires you the most, and why",
    "Can you buy happiness",
    "Imagine you're stuck on the roof of a house that has been carried away by a flood. Which person would you most like to be on the roof with you",
    "Which would you choose: immense wealth in obscurity or poverty and fame or fortune",
    "What animal do you identify with most closely",
    "What is your favorite season and why",
    "Imagine you are attending your dream concert—what songs would you want to be played. What does the stage look like",
    "What's your favorite place to escape from life temporarily?",
    "What's one job you would never want to do",
    "Has a friend ever broken something or yours? How did you react",
    "What's the best memory you have from the last year",
    "How do you feel about politicians openly sharing their religious beliefs",
    "What characteristics or personality traits are most important to you in a politician",
    "If you could trade places with a famous person for a day, who would you like to be and why",
    "If you could learn any new language, which one would you choose and why",
    "If you had to choose between having a personal chef, a housekeeper, or a personal trainer, which would you pick and why",
    "What is the weather like today? How do you feel about it",
    "What season do you like best",
    "What do you wish you could tell someone, and who do you wish you could tell",
    "When you close your eyes and think of where you want to live, what comes to the surface",
    "If you don't believe in reincarnation, forget about that for a minute. What would you like to be reincarnated as ",
    "What are things that you wish people knew about you without your having to tell them",
    "What are a few qualities you dislike in other people, and why",
    "What music makes you want to get up and dance",
    "If you need inspiration and put on your favorite CD, which one is it",
    "If you were in the band, what instrument would you be playing",
    "When do you think about your regrets the most often",
    "What is your most prized possession",
    "What is your favorite lie to tell",
    "Who do you live for",
    "What is a secret about you",
    "What family item has changed your view or ideas about a family member",
    "Write about your best friend as if they were a stranger",
    "If you could build a soundtrack to your life, who would be on it",
    "If you suddenly gained the ability to tell whether someone was lying, would you use it",
    "How would handle life in an arctic climate",
    "Describe your perfect career. Where would it be? Would you want financial or personal fulfillment", "What kind of people would you work with",
    "Who is your ideal presidential candidate",
    "What kind of jobs have you had in the past",
    "What was your major in college. How did you choose it",
    "Where are you from",
    "How would you go about 'saving the world'",
    "If you were to write a book, would it be fiction or non-fiction, What would the subject be",
    "What is your favorite book",
    "What was/is something that your father considered/considers very important?",
    "What is something you liked about your childhood?",
]

export const dailyPrompts = [
    "Write your day in bullet points.",
    "What is it that you would want to change in today?",
    "What are you grateful for today?",
    "What is your biggest concern right now?",
]

export const monthlyPrompts = [
    "3 biggest concerns for this month",
    "3 things that you will be working on to make yourself better this month.",
    "3 things that were good last month.",
    "5 things to do this month.",
]